### ISSUE TITLE
tabindex should skip "send reset link"

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#15]
Right now when you hit tab when the "email address" field is focused the focus moves to the "Send reset link" button. It should go to the "password" field and then to the "log in" button, then back up to the "send reset link" button.

https://github.com/Taoula/firebaseui-react/assets/179361/e2ef9de7-e320-4b8a-8c08-3e752f0ee8a7

I think the way to do this is with `tabindex`.

**Comment by Taoula** [comment]
Fixed in new version.
