### ISSUE TITLE
Handle "send reset link" with no email address

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#17]
Currently, clicking "send reset link" with no email address gives this error: `FirebaseError: Firebase: Error (auth/network-request-failed).`

<img width="1598" alt=" 2024-01-02 at 2 45 24 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/c5503bad-6603-442a-9455-32bdbc7e5e56">

Ideally the "send reset link" button would be disabled (and grayed out?) until there was a valid-looking email address in the email field. If the user clicks that button before a valid email is there then an error should display that says something along the lines of "please enter a valid email address before resetting your password."

**Comment by Taoula** [comment]
Fixed. Will be in new version (not yet published, I'm going to push these fixes together).
