### ISSUE TITLE
Clear the error message when an info message shows up

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#18]
Currently if there's an error message and then I do something that pops up an info message (like resetting my password) then both messages show up:

<img width="419" alt=" 2024-01-02 at 2 50 11 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/acc515d1-e3ec-4d29-a40f-94c14d69f4eb">

I want the error message to clear if there's an info message.

**Comment by Taoula** [comment]
Fixed. Will be in next version.
