### ISSUE TITLE
Improve UI of email password fields and errors

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#21]
Here's what it currently looks like:

<img width="952" alt=" 2024-01-02 at 4 41 49 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/6ad1f4fe-3f04-437a-8b6f-bec35390d25d">

Here's what better styling for an error state for an input fields looks like (from [Tailwind UI input groups](https://tailwindui.com/components/application-ui/forms/input-groups)):

<img width="386" alt=" 2024-01-02 at 4 43 52 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/7351767c-ad56-4e37-9015-b214f4e50d0e">

Specifically, the spacing between the password error text and the password field is too tall and the space between the log in button and the password error text isn't tall enough.

**Comment by Taoula** [comment]
Fixed. Will be in next version.
