### ISSUE TITLE
`fullLabel` field on emailpassword provider doesn't work.

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#22]
With this config:

```js
{
    signInOptions: [
      { provider: "emailpassword", fullLabel: "Log in" },
      "google.com",
    ],
    continueUrl: "https://fileinbox.com/login",
    formLabelStyles: { color: "#fff", fontSize: "0.75rem", fontWeight: "600" },
  }
```

I expect the label on the email password field to be `Log in` but it's "Log in or create account"

<img width="497" alt=" 2024-01-02 at 4 46 11 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/a7fabf1f-c749-46c5-9d96-b88b703f2c14">

**Comment by Taoula** [comment]
Fixed. Will be in next version.
