### ISSUE TITLE
Remove dynamic import requirement for faster loads

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#24]
I think right now we're using `window` for something related to recaptchas for phone logins and that's why we need to import the library dynamically in Next.js.

I'd love to find another way around using `window` (or whatever the problem was that caused us to need dynamic imports) so the component loads faster.

https://github.com/Taoula/firebaseui-react/assets/179361/0b483873-b067-42cd-9a84-9c4bc8a0d290

**Comment by Taoula** [comment]
Fixed in latest version. You can remove the`ssr: false` dynamic import.
