### ISSUE TITLE
Add labels to email/password form fields

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#25]
Like this:

<img width="433" alt=" 2024-01-05 at 5 29 23 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/79a9961d-1ae0-4788-93b1-e7ec624e5bb0">
 
From https://tailwindui.com/components/application-ui/forms/sign-in-forms

**Comment by Taoula** [comment]
@christiangenco I'm not sure I understand. Is it the styling of the current labels you want to change?
