### ISSUE TITLE
Reset password screen UI improvements

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#26]
<img width="857" alt=" 2024-01-13 at 4 21 21 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/dae519d2-bdf6-4a72-b8f9-aa22998af086">

1. Hide "Reset password" header
2. Put the email in a non-editable email field and include the "Email" label above it.

This screen should look just like the email login screen but with "New Password" instead of "Password" and the email field disabled and no "send reset link" button.

<img width="416" alt=" 2024-01-13 at 4 22 34 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/80cc39e8-c93e-408e-be9f-f49a2a27fab1">

**Comment by Taoula** [comment]
Fixed in new version.
