### ISSUE TITLE
Add "skip" button to reset password page

### ISSUE THREAD

**Issue by christiangenco** [Taoula/firebaseui-react#27]
Because we're just doing passwordless authentication it'd be cool of users could skip making a new password and just log in with a magic link. This button should just trigger `signInSuccessWithAuthResult`.

<img width="431" alt=" 2024-01-13 at 4 24 51 PM" src="https://github.com/Taoula/firebaseui-react/assets/179361/571b8660-f131-40ef-92bd-e4c69aa16be1">

**Comment by Taoula** [comment]
Added in new version.
